/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import DBO.User;
import DBO.UserDOA;
import Models.MonModele;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JButton;
import javax.swing.JFrame;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Font;

/**
 *
 * @author Mohamed EL HADDAD
 */
public class UserPage extends javax.swing.JFrame {

	private int indice;
    void Load()
    {
    	
        Tusers.setModel(new MonModele(new UserDOA().getAll()));
                
      }
    public UserPage() {
        initComponents();
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitre = new javax.swing.JLabel();
        LblTitre.setFont(new Font("Tahoma", Font.BOLD, 16));
        jScrollPane1 = new javax.swing.JScrollPane();
        Tusers = new javax.swing.JTable();
     
       /* Tusers.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusGained(FocusEvent e) {
        		TuserDelete(e);
        		
        	}
        });*/
        TxtLogin = new javax.swing.JTextField();
        TxtPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnAdd = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitre.setText("GESTION DES UTILISATEURS");

        Tusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tusers);

        jLabel1.setText("LOGIN");

        jLabel2.setText("PASSWORD");

        BtnAdd.setText("ADD");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnClose.setText("Return Home");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        
        JButton btnNewButton = new JButton("Delete");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		int indice = Tusers.getSelectedRow();
        		
        		if(indice!=-1) {
        			
        			String Login =String.valueOf(Tusers.getValueAt(indice,0));
        			
        			UserDOA dao = new UserDOA();
        			
        	        dao.delete(Login);
        	        
        	        Load();
        		}
        	        
        	}
        });
        
        JButton btnNewButton_1 = new JButton("Update");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) 
        	{
        		
        		
        		int indice = Tusers.getSelectedRow(); 
        		if(indice!=-1) {
        			
        			//dispose ferme      new index.setVisible(true)
        			String Login =String.valueOf(Tusers.getValueAt(indice,0));
        			
        			String Password=TxtPassword.getText();
        			
        			UserDOA dao = new UserDOA();
        			
        	        dao.update(Password,Login);
        	        
        	        Load();
        	        
        	        TxtPassword.setText("");
        	        TxtLogin.setText("");
        		}
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(161)
        			.addComponent(LblTitre, GroupLayout.PREFERRED_SIZE, 315, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
        			.addComponent(BtnClose)
        			.addGap(25))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(41)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 486, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2)
        						.addComponent(jLabel1))
        					.addGap(22)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(TxtLogin)
        						.addComponent(TxtPassword, GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
        					.addGap(99)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(BtnAdd, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnNewButton, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnNewButton_1, Alignment.LEADING))))
        			.addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(24)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LblTitre, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(BtnClose))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(TxtLogin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1)
        				.addComponent(BtnAdd))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(TxtPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel2))
        				.addComponent(btnNewButton))
        			.addGap(18)
        			.addComponent(btnNewButton_1)
        			.addPreferredGap(ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
        			.addGap(50))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
       
    	UserDOA dao = new UserDOA();
    	
        User user = new User(TxtLogin.getText(), TxtPassword.getText());
        
        dao.Insert(user);
        
        Load();
                
        TxtLogin.setText("");
        TxtPassword.setText("");
        
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomePage h=new HomePage();
        h.frame.setVisible(true);
    }//GEN-LAST:event_BtnCloseActionPerformed

    // -----------------------------------------------------------Mouad--------------------------------------
    
    /*private void TuserDelete(FocusEvent e) {
    	
    	 daoUsers dao = new daoUsers();
    	 
         User user = new User(TxtLogin.getText(), TxtPassword.getText());
         dao.Delete(user);
         Load();
    }
    */
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnClose;
    private javax.swing.JLabel LblTitre;
    private javax.swing.JTable Tusers;
    private javax.swing.JTextField TxtLogin;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
	public javax.swing.JFrame frame;
}

